name: brain-fly
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu126
    - brian2cuda==1.0a7
    - torch
    - tqdm
    - flygym==1.2.1
    - mujoco>=3.3
    - glfw
    - dm-control
    - pygame
    - fpdf2
  - numpy=1.26.4
  - jupyter
  - ipykernel
  - pandas
  - joblib
  - pyarrow
  - scipy
  - matplotlib
